#!/usr/bin/env bash
# Build / run / package the Autonomic RR watch app.
#   ./build.sh sim     build + launch in the Connect IQ simulator
#   ./build.sh device  build a sideloadable .prg into dist/
set -euo pipefail

SDK_ROOT="$HOME/Library/Application Support/Garmin/ConnectIQ/Sdks"
SDK="$(ls -d "$SDK_ROOT"/connectiq-sdk-mac-* 2>/dev/null | sort -V | tail -1)"
KEY="$HOME/.garmin-ciq/developer_key.der"
DEVICE="${DEVICE:-venu445mm}"
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/dist"

[ -n "$SDK" ] || { echo "No Connect IQ SDK found under $SDK_ROOT"; exit 1; }
[ -f "$KEY" ] || { echo "Missing developer key at $KEY"; exit 1; }
export PATH="$SDK/bin:$PATH"
mkdir -p "$OUT"

# The watch app's version IS the phone app's version — they ship as one product
# and a user reporting "1.25.2" must mean the same thing on both. Connect IQ
# manifests carry no version field (the store sets it at publish time), so it is
# generated here from mobile/app.json rather than hand-copied into a constant
# that would silently drift.
VERSION="$(python3 -c "import json;print(json.load(open('$HERE/../mobile/app.json'))['expo']['version'])")"
cat > "$HERE/resources/strings/version.xml" <<XML
<!-- GENERATED by build.sh from mobile/app.json. Do not edit. -->
<strings>
    <string id="AppVersion">$VERSION</string>
</strings>
XML

case "${1:-sim}" in
  store)
    # The multi-device package the Connect IQ store takes. Builds every product
    # listed in the manifest, so adding a device there is a claim that it works.
    monkeyc -e -f "$HERE/monkey.jungle" -o "$OUT/Autonomic.iq" -y "$KEY" -w -r
    echo "Built $OUT/Autonomic.iq for upload to apps-developer.garmin.com"
    ;;
  sim)
    monkeyc -d "$DEVICE" -f "$HERE/monkey.jungle" -o "$OUT/AutonomicRr.prg" -y "$KEY" -w -l 1
    connectiq &
    sleep 5
    monkeydo "$OUT/AutonomicRr.prg" "$DEVICE"
    ;;
  device)
    # -r strips debug info; -e produces the loadable package
    monkeyc -d "$DEVICE" -f "$HERE/monkey.jungle" -o "$OUT/AutonomicRr.prg" -y "$KEY" -w -l 1 -r
    echo
    echo "Built $OUT/AutonomicRr.prg"
    echo "Sideload: drag it into GARMIN/Apps/ on the watch (OpenMTP), then eject."
    ;;
  *)
    echo "usage: $0 [sim|device]"; exit 1;;
esac
