#!/usr/bin/env bash
# Build / run / package the Autonomic RR watch app.
#   ./build.sh sim     build + launch in the Connect IQ simulator
#   ./build.sh device  build a sideloadable .prg into dist/
set -euo pipefail

SDK_ROOT="$HOME/Library/Application Support/Garmin/ConnectIQ/Sdks"
SDK="$(ls -d "$SDK_ROOT"/connectiq-sdk-mac-* 2>/dev/null | sort -V | tail -1)"
KEY="$HOME/.garmin-ciq/developer_key.der"
DEVICE="${DEVICE:-venu445mm}"
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/dist"

[ -n "$SDK" ] || { echo "No Connect IQ SDK found under $SDK_ROOT"; exit 1; }
[ -f "$KEY" ] || { echo "Missing developer key at $KEY"; exit 1; }
export PATH="$SDK/bin:$PATH"
mkdir -p "$OUT"

# The watch app's version IS the phone app's version — they ship as one product
# and a user reporting "1.25.2" must mean the same thing on both. Connect IQ
# manifests carry no version field (the store sets it at publish time), so it is
# generated here from mobile/app.json rather than hand-copied into a constant
# that would silently drift.
# Every product in the manifest must have glyph assets for its screen family.
# Nothing scales at runtime any more (see Theme.mc), so a family without them
# would fall back to the 96px masters and draw a heart four times too big —
# and, worse, the compiler is perfectly happy to build it. This is the check
# that keeps "listing a device is a claim that it works" true.
python3 - "$HERE" <<'PYCHECK'
import json, os, re, sys
here = sys.argv[1]
devices = os.path.expanduser(
    "~/Library/Application Support/Garmin/ConnectIQ/Devices")
missing = []
for d in re.findall(r'<iq:product id="([^"]+)"',
                    open(os.path.join(here, "manifest.xml")).read()):
    c = os.path.join(devices, d, "compiler.json")
    if not os.path.exists(c):
        missing.append("%s (device not installed in the SDK)" % d)
        continue
    fam = json.load(open(c))["deviceFamily"]
    if not os.path.exists(os.path.join(here, "resources-%s" % fam,
                                       "drawables", "heart.png")):
        missing.append("%s -> resources-%s/" % (d, fam))
if missing:
    print("Missing glyph assets. Run tools/gen-glyphs.py.")
    for m in missing:
        print("  " + m)
    sys.exit(1)
PYCHECK

VERSION="$(python3 -c "import json;print(json.load(open('$HERE/../mobile/app.json'))['expo']['version'])")"
cat > "$HERE/resources/strings/version.xml" <<XML
<!-- GENERATED by build.sh from mobile/app.json. Do not edit. -->
<strings>
    <string id="AppVersion">$VERSION</string>
</strings>
XML

case "${1:-sim}" in
  store)
    # The multi-device package the Connect IQ store takes. Builds every product
    # listed in the manifest, so adding a device there is a claim that it works.
    monkeyc -e -f "$HERE/monkey.jungle" -o "$OUT/Autonomic.iq" -y "$KEY" -w -r
    echo "Built $OUT/Autonomic.iq for upload to apps-developer.garmin.com"
    ;;
  sim)
    monkeyc -d "$DEVICE" -f "$HERE/monkey.jungle" -o "$OUT/AutonomicRr.prg" -y "$KEY" -w -l 1
    connectiq &
    sleep 5
    monkeydo "$OUT/AutonomicRr.prg" "$DEVICE"
    ;;
  device)
    # -r strips debug info; -e produces the loadable package
    monkeyc -d "$DEVICE" -f "$HERE/monkey.jungle" -o "$OUT/AutonomicRr.prg" -y "$KEY" -w -l 1 -r
    echo
    echo "Built $OUT/AutonomicRr.prg"
    echo "Sideload: drag it into GARMIN/Apps/ on the watch (OpenMTP), then eject."
    ;;
  *)
    echo "usage: $0 [sim|device]"; exit 1;;
esac
