import SwiftUI

/**
 * Design tokens + shared controls, matching the imported Claude Design mock
 * (Watch Companion.dc.html): black screen, red accent, rounded cards/pills.
 * Colors come from the asset catalog generated by expo-target.config.js.
 */
enum DS {
    static let accent = Color("accent")          // #e03127
    static let blue = Color("accentBlue")        // #4aa3f0
    static let amber = Color("accentAmber")      // #e0a030
    static let green = Color("accentGreen")      // #3ec46d
    static let card = Color("cardBg")            // #161618
    static let tile = Color("tileBg")            // #131315
    static let dim = Color("textDim")            // #8a8a92

    /// Shared delta color rule: <20 green · 20–29 amber · ≥30 red.
    static func deltaColor(_ delta: Double) -> Color {
        delta >= 30 ? accent : delta >= 20 ? amber : green
    }
}

struct PrimaryButton: View {
    let title: String
    var color: Color = DS.accent
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            Text(title)
                .font(.system(size: 16, weight: .bold))
                .frame(maxWidth: .infinity)
                .padding(.vertical, 12)
                .background(color, in: RoundedRectangle(cornerRadius: 16))
        }
        .buttonStyle(.plain)
    }
}

struct SecondaryButton: View {
    let title: String
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            Text(title)
                .font(.system(size: 13.5, weight: .semibold))
                .foregroundStyle(DS.dim)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 10)
                .background(DS.card, in: RoundedRectangle(cornerRadius: 15))
        }
        .buttonStyle(.plain)
    }
}

struct StatTile: View {
    let label: String
    let value: String
    var valueColor: Color = .primary

    var body: some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(label.uppercased())
                .font(.system(size: 10, weight: .bold))
                .kerning(0.5)
                .foregroundStyle(DS.dim)
            Text(value)
                .font(.system(size: 20, weight: .heavy, design: .rounded))
                .foregroundStyle(valueColor)
                .monospacedDigit()
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(.vertical, 9)
        .padding(.horizontal, 11)
        .background(DS.tile, in: RoundedRectangle(cornerRadius: 13))
    }
}

/// Ring countdown, stroke rotated to start at 12 o'clock (mock's rings).
struct RingProgress: View {
    let progress: Double // 0…1 = elapsed fraction
    let color: Color

    var body: some View {
        ZStack {
            Circle().stroke(Color.white.opacity(0.07), lineWidth: 9)
            Circle()
                .trim(from: 0, to: max(0.001, min(1, progress)))
                .stroke(color, style: StrokeStyle(lineWidth: 9, lineCap: .round))
                .rotationEffect(.degrees(-90))
                .animation(.linear(duration: 0.9), value: progress)
        }
    }
}

struct DeltaChip: View {
    let delta: Double?

    var body: some View {
        let color = delta.map { DS.deltaColor($0) } ?? DS.dim
        let text = delta.map { "Δ \($0 >= 0 ? "+" : "")\(Int($0.rounded())) bpm" } ?? "Δ —"
        Text(text)
            .font(.system(size: 12.5, weight: .heavy))
            .monospacedDigit()
            .foregroundStyle(color)
            .padding(.horizontal, 11)
            .padding(.vertical, 3)
            .background(color.opacity(0.12), in: Capsule())
            .overlay(Capsule().stroke(color.opacity(0.33), lineWidth: 1))
    }
}

struct BeatingHeart: View {
    var size: CGFloat = 26
    var beating = true
    @State private var beat = false

    var body: some View {
        Image(systemName: "heart.fill")
            .font(.system(size: size))
            .foregroundStyle(DS.accent)
            .scaleEffect(beat ? 1.18 : 1.0)
            .onAppear {
                guard beating else { return }
                withAnimation(.easeInOut(duration: 0.5).repeatForever(autoreverses: true)) { beat = true }
            }
    }
}

func fmtCountdown(_ seconds: Int) -> String {
    "\(seconds / 60):" + String(format: "%02d", max(0, seconds) % 60)
}
