import SwiftUI

/**
 * Design tokens + shared controls, matching the imported Claude Design mock
 * (Watch Companion.dc.html): black screen, red accent, rounded cards/pills.
 * Colors come from the asset catalog generated by expo-target.config.js.
 */
enum DS {
    static let accent = Color("accent")          // #e03127
    static let blue = Color("accentBlue")        // #4aa3f0
    static let amber = Color("accentAmber")      // #e0a030
    static let green = Color("accentGreen")      // #3ec46d
    static let purple = Color(red: 0.62, green: 0.42, blue: 0.96)  // #9d6bf5 — orthostatic events
    static let card = Color("cardBg")            // #161618
    static let tile = Color("tileBg")            // #131315
    static let dim = Color("textDim")            // #8a8a92
    /// Dark grey for held-but-stale data: shown while no HR signal / signal dropped.
    static let faint = Color.white.opacity(0.3)

    /// Shared delta color rule: <20 green · 20–29 amber · ≥30 red.
    static func deltaColor(_ delta: Double) -> Color {
        delta >= 30 ? accent : delta >= 20 ? amber : green
    }

    /// Metric numerals — Manrope ExtraBold, matching the phone app's readouts
    /// (`fonts.numHeavy`). Bundled via the watch Info.plist UIAppFonts.
    static func number(_ size: CGFloat) -> Font { .custom("Manrope-ExtraBold", size: size) }
}

struct PrimaryButton: View {
    let title: String
    var color: Color = DS.accent
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            Text(title)
                .font(.system(size: 16, weight: .bold))
                .frame(maxWidth: .infinity)
                .padding(.vertical, 12)
                .background(color, in: RoundedRectangle(cornerRadius: 16))
        }
        .buttonStyle(.plain)
    }
}

struct SecondaryButton: View {
    let title: String
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            Text(title)
                .font(.system(size: 13.5, weight: .semibold))
                .foregroundStyle(DS.dim)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 10)
                .background(DS.card, in: RoundedRectangle(cornerRadius: 15))
        }
        .buttonStyle(.plain)
    }
}

struct StatTile: View {
    let label: String
    let value: String
    var valueColor: Color = .primary

    var body: some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(label.uppercased())
                .font(.system(size: 10, weight: .bold))
                .kerning(0.5)
                .foregroundStyle(DS.dim)
            Text(value)
                .font(DS.number(20))
                .foregroundStyle(valueColor)
                .monospacedDigit()
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(.vertical, 9)
        .padding(.horizontal, 11)
        .background(DS.tile, in: RoundedRectangle(cornerRadius: 13))
    }
}

/// Ring countdown, stroke rotated to start at 12 o'clock (mock's rings).
struct RingProgress: View {
    let progress: Double // 0…1 = elapsed fraction
    let color: Color

    var body: some View {
        ZStack {
            Circle().stroke(Color.white.opacity(0.07), lineWidth: 5)
            Circle()
                .trim(from: 0, to: max(0.001, min(1, progress)))
                .stroke(color, style: StrokeStyle(lineWidth: 5, lineCap: .round))
                .rotationEffect(.degrees(-90))
                .animation(.linear(duration: 0.9), value: progress)
        }
    }
}

struct DeltaChip: View {
    let delta: Double?
    /// Signal lost: keep showing the held delta, but greyed (mirrors HrReadout).
    var stale: Bool = false

    var body: some View {
        let color = delta == nil ? DS.dim : stale ? DS.faint : DS.deltaColor(delta!)
        let text = delta.map { "Δ \($0 >= 0 ? "+" : "")\(Int($0.rounded()))" } ?? "Δ 00"
        Text(text)
            .font(DS.number(12.5))
            .monospacedDigit()
            .foregroundStyle(color)
            .padding(.horizontal, 11)
            .padding(.vertical, 3)
            .background(color.opacity(0.12), in: Capsule())
            .overlay(Capsule().stroke(color.opacity(0.33), lineWidth: 1))
    }
}

struct BeatingHeart: View {
    var size: CGFloat = 26
    /// Live BPM — drives the beat rate (one contraction per cardiac cycle).
    /// nil falls back to a gentle idle pulse.
    var bpm: Double? = nil
    var beating = true
    @State private var beat = false

    /// Bucket BPM to the nearest 5 so the repeating animation only restarts on a
    /// meaningful rate change, not on every 1 Hz sample.
    private var bucket: Int { bpm.map { Int(($0 / 5).rounded()) * 5 } ?? 0 }

    /// Half-cycle duration: a full up→down (autoreverse) equals one beat period
    /// (60/bpm). Clamped so extreme rates stay legible.
    private var halfCycle: Double {
        guard let bpm, bpm > 20 else { return 0.5 }
        return max(0.16, min(0.9, 30.0 / bpm))
    }

    var body: some View {
        Image(systemName: "heart.fill")
            .font(.system(size: size))
            .foregroundStyle(DS.accent)
            .scaleEffect(beat ? 1.18 : 1.0)
            .onAppear { restart() }
            .onChange(of: bucket) { _, _ in restart() }
    }

    private func restart() {
        guard beating else { return }
        beat = false
        withAnimation(.easeInOut(duration: halfCycle).repeatForever(autoreverses: true)) { beat = true }
    }
}

func fmtCountdown(_ seconds: Int) -> String {
    "\(seconds / 60):" + String(format: "%02d", max(0, seconds) % 60)
}
