#!/usr/bin/env python3
"""Generate the per-screen-size glyph assets from the 96px masters.

Connect IQ's `Dc.drawScaledBitmap` exists on only 47 of the ~117 devices the
app can otherwise run on -- and it is NOT a graceful absence: the heart is the
first thing the home screen draws, so a device without it crashes on launch
with "Could not find symbol 'drawScaledBitmap'". fenix 5/6, vivoactive 3/4/5,
every Forerunner up to the 255, MARQ, Venu 1, Venu Sq, Descent and Instinct are
all on the wrong side of that line.

So nothing scales at runtime any more. Each screen family gets the glyph at the
exact pixel size that family draws it at, in `resources-<family>/drawables/`,
which the default jungle picks up automatically -- no jungle entries, no
`has :drawScaledBitmap` branch, and the same anti-aliased artwork everywhere.

The sizes below are DERIVED FROM THE CALL SITES and must move with them:

  heart  Home.mc  item h = screenH * 0.21, disc r = h * 0.29, glyph r = r * 0.56
  check  Theme.mc `completion`, r = screenH * 0.052

Run after adding a product to manifest.xml; build.sh fails the build if a
product's family has no assets.
"""
import json, os, re, sys, glob
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DEVICES = os.path.expanduser(
    "~/Library/Application Support/Garmin/ConnectIQ/Devices")

HEART = 0.21 * 0.29 * 0.56 * 2   # glyph DIAMETER as a fraction of screen height
CHECK = 0.052 * 2

# Square glyphs: one ratio, drawn centred on a point.
MASTERS = {"heart.png": HEART, "heart_dim.png": HEART, "check.png": CHECK}

# The logo is the odd one out — it is not square and it is not centred on a
# point, it is a wordmark that has to FIT the CustomMenu's title band. The band
# is screenHeight * 0.21 (Home.menu) and HomeTitle stacks the mark over the
# "Autonomic" text inside it, so a fixed 104x56 master overflowed the band on
# every screen smaller than the Venu 4 and pushed the wordmark down into the
# first row. Worst on a 176px Instinct: a 36px band holding a 56px logo.
#
# The ratio is taken FROM the 454px master (56/454, 104/454) so the device the
# app already ships on renders the identical pixels, and every smaller screen
# gets the same proportion rather than the same size.
LOGO_H = 56 / 454.0
LOGO_W = 104 / 454.0

GENERATED_XML = """<!-- GENERATED by tools/gen-glyphs.py. Do not edit. -->
<drawables>
    <bitmap id="Heart" filename="heart.png" />
    <bitmap id="HeartDim" filename="heart_dim.png" />
    <bitmap id="CheckBadge" filename="check.png" />
    <bitmap id="Logo" filename="logo.png" />
</drawables>
"""


def families(manifest):
    """(family, screenHeight) for every product the manifest claims."""
    ids = re.findall(r'<iq:product id="([^"]+)"', open(manifest).read())
    out = {}
    for d in ids:
        p = os.path.join(DEVICES, d, "compiler.json")
        if not os.path.exists(p):
            print("  ! %s not installed in the SDK, skipped" % d)
            continue
        c = json.load(open(p))
        out.setdefault(c["deviceFamily"], set()).add(c["resolution"]["height"])
    for fam, hs in sorted(out.items()):
        assert len(hs) == 1, "%s has mixed heights %s" % (fam, hs)
        yield fam, hs.pop()


def main():
    manifest = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "manifest.xml")
    made = 0
    for fam, h in families(manifest):
        out = os.path.join(ROOT, "resources-%s" % fam, "drawables")
        os.makedirs(out, exist_ok=True)
        src = Image.open(os.path.join(ROOT, "resources", "drawables", "logo.png"))
        src.resize((max(8, round(h * LOGO_W)), max(6, round(h * LOGO_H))),
                   Image.LANCZOS).save(os.path.join(out, "logo.png"))
        made += 1
        for name, ratio in MASTERS.items():
            size = max(8, round(h * ratio))
            src = Image.open(os.path.join(ROOT, "resources", "drawables", name))
            # LANCZOS is what drawScaledBitmap did on the devices that had it,
            # so the 47 that keep working keep the pixels they already shipped.
            src.resize((size, size), Image.LANCZOS).save(
                os.path.join(out, name))
            made += 1
        # The ids have to be redefined here, not just the files dropped in:
        # a resource directory later on the path overrides an id, it does not
        # inherit a filename. Only the three glyphs are listed, so the logo and
        # the launcher icon keep coming from the base resources.
        with open(os.path.join(out, "drawables.xml"), "w") as f:
            f.write(GENERATED_XML)
        print("  %-24s %3dpx screen -> heart %2dpx  check %2dpx  logo %3dx%2d"
              % (fam, h, round(h * HEART), round(h * CHECK),
                 round(h * LOGO_W), round(h * LOGO_H)))
    print("wrote %d assets" % made)


if __name__ == "__main__":
    main()
